### ISSUE TITLE
MODULE FAILURE !  

### ISSUE THREAD

**Issue by haisamido** [TomasTomecek/ansible-nginx-container#1]
on CentOS7.x I get a MODULE FAILURE (below). Only change I made was `container_engine: docker `. The details are below when I run:

`sudo ansible-playbook -vvv provision-container.yml`

`Docker version 1.13.1, build dded712/1.13.1`

```
ansible 2.4.2.0
  config file = /home/ssmodev/Development/ansible-nginx-container/ansible.cfg
  configured module search path = [u'/home/ssmodev/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

```
sudo pip install docker-py
[sudo] password for ssmodev: 
Requirement already satisfied (use --upgrade to upgrade): docker-py in /usr/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): websocket-client>=0.32.0 in /usr/lib/python2.7/site-packages (from docker-py)
Requirement already satisfied (use --upgrade to upgrade): requests!=2.11.0,>=2.5.2 in /usr/lib/python2.7/site-packages (from docker-py)
Requirement already satisfied (use --upgrade to upgrade): backports.ssl-match-hostname>=3.5; python_version < "3.5" in /usr/lib/python2.7/site-packages (from docker-py)
Requirement already satisfied (use --upgrade to upgrade): ipaddress>=1.0.16; python_version < "3.3" in /usr/lib/python2.7/site-packages (from docker-py)
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.0 in /usr/lib/python2.7/site-packages (from docker-py)
Requirement already satisfied (use --upgrade to upgrade): docker-pycreds>=0.2.1 in /usr/lib/python2.7/site-packages (from docker-py)

```

Error:

```
TASK [Make the base image available locally] *******************************************************************************************************************************************************************************
task path: /home/ssmodev/Development/ansible-nginx-container/provision-container.yml:17
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/cloud/docker/docker_image.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: ssmodev
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1534870140.6-146339557218302 `" && echo ansible-tmp-1534870140.6-146339557218302="` echo /root/.ansible/tmp/ansible-tmp-1534870140.6-146339557218302 `" ) && sleep 0'
<localhost> PUT /tmp/tmpbURoat TO /root/.ansible/tmp/ansible-tmp-1534870140.6-146339557218302/docker_image.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1534870140.6-146339557218302/ /root/.ansible/tmp/ansible-tmp-1534870140.6-146339557218302/docker_image.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1534870140.6-146339557218302/docker_image.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1534870140.6-146339557218302/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_DF2wjl/ansible_module_docker_image.py", line 457, in <module>
    main()
  File "/tmp/ansible_DF2wjl/ansible_module_docker_image.py", line 400, in main
    image_id = manager.build()
  File "/tmp/ansible_DF2wjl/ansible_module_docker_image.py", line 292, in build
    stream = self.client.build(self.path, dockerfile=self.dockerfile, tag=':'.join([self.name, self.tag]), nocache=self.nocache, rm=True, stream=True)
  File "/usr/lib/python2.7/site-packages/docker/api/build.py", line 25, in build
    raise TypeError("Either path or fileobj needs to be provided.")
TypeError: Either path or fileobj needs to be provided.

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_DF2wjl/ansible_module_docker_image.py\", line 457, in <module>\n    main()\n  File \"/tmp/ansible_DF2wjl/ansible_module_docker_image.py\", line 400, in main\n    image_id = manager.build()\n  File \"/tmp/ansible_DF2wjl/ansible_module_docker_image.py\", line 292, in build\n    stream = self.client.build(self.path, dockerfile=self.dockerfile, tag=':'.join([self.name, self.tag]), nocache=self.nocache, rm=True, stream=True)\n  File \"/usr/lib/python2.7/site-packages/docker/api/build.py\", line 25, in build\n    raise TypeError(\"Either path or fileobj needs to be provided.\")\nTypeError: Either path or fileobj needs to be provided.\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
```

`

**Comment by TomasTomecek** [comment]
`docker-py` is the old, unmaintained version, please install `docker`:
```
$ pip install docker
```

**Comment by TomasTomecek** [comment]
Closing, since this got stalled. Feel free to reopen if this is still happening.
